[theme]
primaryColor = "#2ecc71"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
showErrorDetails = true

# Configuración específica para v2
[global]
developmentMode = false
dataFrameSerialization = "arrow"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
